Extend subscriptions
bugout-dev/moonstream pull request #241
Opened 2021-09-07 15:34 UTC by Andrei-Dolgolev

## Changes

## How to test these changes?

## Related issues

2021-09-07 15:36 UTC, Andrei-Dolgolev commented
- [ ]  update required python -m moonstream.admin.cli subtypes update -i 'ethereum_blockchain' -c 'input:address' 'tag:nfts' | jq
- [ ]  update required python -m moonstream.admin.cli subtypes update -i 'ethereum_txpool' -c 'input:address' 'tag:nfts' | jq
- [ ]  update required python -m moonstream.admin.cli subtypes update -i 'ethereum_whalewatch' -c  | jq

2021-09-08 14:49 UTC, kompotkot requested changes

2021-09-08 14:49 UTC, kompotkot commented on backend/moonstream/admin/subscription_types.py
> +    choices: Optional[List[str]],
= None

2021-09-08 14:49 UTC, kompotkot commented on backend/moonstream/admin/subscription_types.py
>      except Exception as e:
```
    except BugoutResponseException as e:
        raise MoonstreamHTTPException(status_code=e.status_code, detail=e.detail)
    except Exception as e:
        raise MoonstreamHTTPException(status_code=500, internal_error=e)
```

2021-09-08 14:49 UTC, kompotkot commented on backend/moonstream/data.py
> +    choices: Optional[List[str]]
= None

2021-09-08 14:49 UTC, kompotkot commented on backend/moonstream/providers/bugout.py
> +allowed_tags = ["nfts"]
This variable not used nowhere in this PR

2021-09-09 12:13 UTC, kompotkot approved these changes
lg

2021-09-09 13:09 UTC, merged