Add abi url to moonstream subscriptions
bugout-dev/moonstream pull request #342
Opened 2021-10-26 14:00 UTC by Andrei-Dolgolev

## Changes

## How to test these changes?

## Related issues

2021-11-03 14:56 UTC, kompotkot requested changes

2021-11-03 14:56 UTC, kompotkot commented on backend/moonstream/admin/subscriptions.py
> +def cli_migrate_subscriptions(args: argparse.Namespace) -> None:
I think better to have cli funcs in cli.py file

2021-11-03 14:56 UTC, kompotkot commented on backend/moonstream/routes/subscriptions.py
> +        "bucket": None,
Why do we need to store bucket? It will be the same during all time

2021-11-03 14:56 UTC, kompotkot commented on backend/moonstream/routes/subscriptions.py
> +            f"abi/v1/{resource.resource_data['address']}/{resource.id}/abi.json"
We can remove `abi/` at start of the line

2021-11-03 14:56 UTC, kompotkot commented on backend/moonstream/settings.py
> +SMARTCONTRACTS_ABI_BUCKET = os.environ.get("SMARTCONTRACTS_ABI_BUCKET")
`MOONSTREAM_` prefix as for all moonstream vars

2021-11-08 14:10 UTC, kompotkot commented
@bugout-dev check
- [ ] Add env var `MOONSTREAM_SMARTCONTRACTS_ABI_BUCKET`

2021-11-09 11:59 UTC, peersky approved these changes
lgtm

2021-11-09 12:59 UTC, merged