Landing improvements (May 5)
bugout-dev/moonstream pull request #602
Opened 2022-05-05 19:03 UTC by kellan-simiotics

## Changes

Text and style changes to landing page based on latest designs.

## How to test these changes?

Tested locally.

## Related issues

2022-05-05 19:31 UTC, peersky commented
Can you center out this section on mobile screen and also reduce paddings on small screen size. Also add `minH="100vh"` for any `<GridItem>` that misses it
<img width="308" alt="image" src="https://user-images.githubusercontent.com/61459744/167011427-b2ac5e68-4898-4ea5-9a0b-f8d058bf6632.png">

2022-05-05 19:33 UTC, peersky commented
<img width="308" alt="image" src="https://user-images.githubusercontent.com/61459744/167011807-3d949f12-b369-44d0-97da-72996f378164.png">
More padding between button and cards on mobile view

2022-05-05 19:35 UTC, peersky commented
<img width="1083" alt="image" src="https://user-images.githubusercontent.com/61459744/167012132-400b9761-7f60-4122-929b-0ecf30b9f323.png">
This section text is very small on large screen (3000px here)

2022-05-05 19:39 UTC, peersky commented
<img width="1378" alt="image" src="https://user-images.githubusercontent.com/61459744/167012669-a37e95f9-8c6b-465d-bf68-c364d291aec3.png">
Seems to be aligned with card in one line on smaller screen size but on >2560 becomes padded

2022-05-05 19:43 UTC, peersky commented
In mockup text looks bigger and also subheader is bolder. Can you try using semibold or `weight` property on text there and try to make title text bigger ? 
<img width="1839" alt="image" src="https://user-images.githubusercontent.com/61459744/167013290-79b62cba-cccb-4b2f-8609-87cc8a88c415.png">

2022-05-05 19:44 UTC, peersky commented
Here also, see if you can make text weight a bit bolder
<img width="1839" alt="image" src="https://user-images.githubusercontent.com/61459744/167013542-802771fc-bb72-44ad-a086-78ffe76f1064.png">

2022-05-05 19:46 UTC, peersky commented
Can you make steps in bolder? Will look better

<img width="1856" alt="image" src="https://user-images.githubusercontent.com/61459744/167013826-faa8e18b-9fa5-42ea-991b-d832d9c86c62.png">

2022-05-05 19:46 UTC, peersky requested changes
changes requested

2022-05-05 19:46 UTC, peersky commented on frontend/pages/index.js
> +  const JoinDiscordButton = () => {
If you want to have reusable button styling then define it it in theme/button under a new `discordButton` variant, that way we will be able to reuse styling across other pages and components

2022-05-05 19:46 UTC, peersky commented on frontend/pages/index.js
> +        onClick={() => {
OnClick should be realized in JoinDiscordButton implementation

2022-05-05 19:46 UTC, peersky commented on frontend/pages/index.js
> +        Join our Discord
Button name should be realized in button implementation (passed here as props)

2022-05-05 19:46 UTC, peersky commented on frontend/pages/index.js
> +  const MilestoneBox = ({ headingText, description }) => {
Move this to components and export as `chakra(MilestoneBox)`

2022-05-05 19:46 UTC, peersky commented on frontend/pages/index.js
> +                <chakra.h2
use <Heading as="h2" ... > instead

2022-05-05 19:46 UTC, peersky commented on frontend/pages/index.js
> +                paddingLeft="15%"
Paddings on left and right on grid item should be equal. Use ` px={["7%", null, "12%", "15%"]}` or `px="7%"` and solve any other required paddings by using css aligning/justifying, if that's not enough - You can add any additional paddings you need in child components of GridItem

2022-05-05 19:46 UTC, peersky commented on frontend/pages/index.js
> +                paddingLeft="15%"
<img width="725" alt="image" src="https://user-images.githubusercontent.com/61459744/167010820-52a81323-2339-4187-9bac-22e5a361ea8e.png">

2022-05-05 19:50 UTC, peersky commented on frontend/pages/index.js
> +        onClick={() => {
Expected code would look like 
page
```jsx
<Button variant="DiscordButton" onClick={() => { mixpanel.track()}}>Join us in discord</Button>
```

That way also you can add mixpanel track property to identify from which section button was pressed

2022-05-06 16:40 UTC, kellan-simiotics commented
@peersky @zomglings Please review changes.

2022-05-06 17:21 UTC, zomglings approved these changes
lgtm

2022-05-06 17:22 UTC, merged